### PR TITLE
updated from your website, added package.el headers

### PR DESCRIPTION
**Pull request by jpkotta**
I'm planning on submitting this to melpa (http://melpa.milkbox.net/), so I figured I'd get the latest version.  I don't think the package.el headers are necessary for melpa, but they would be for something like elpa.

### CODE REVIEW

**Comment by davep** [comment]
I'm ashamed to say I've only just noticed this. I'm just getting back into heavily using GNU emacs after a long period of being fairly inactive and, because of this, the whole package management thing is actually new to me. I'm going to be doing some reading up on what's involved and hope to tidy up all my code -- boquote.el included -- to better fit with how emacs is doing things these days.

**Comment by davep** [comment]
Coming back to looking at package systems I was tinkering with boxquote and made similar changes before remembering this was here. So... thanks for doing this, sorry I made a conflicting change (still trying to figure everything out). Similar changes are being made so it was worth the effort.

**Comment by tarsius** [comment]
Thanks!

> Coming back to looking at package systems

Since you are using the plural... By now I have released my own: [`borg`](https://github.com/emacscollective/borg) ;-)

**Comment by davep** [comment]
Just when I'd managed to get the hang of one, almost..... ;)

I'll be sure to take a look. :)

**Comment by tarsius** [comment]
You should also check out [`use-package`](https://github.com/jwiegley/use-package). It's not a package manager, but a tool to keep your configuration under control.

**Pull request closed without merging**
