### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by tarsius**

### CODE REVIEW

**Comment by davep** [comment]
Good catch, thanks.

**Comment by tarsius** [comment]
I use `codespell` for this. It's a nice tool but maybe its not such a good idea to run it on all the elisp packages one has installed... doesn't mix well with a bit of ocd...

**Comment by tarsius** [comment]
Speaking of which...

You might want to create a new release for the last two commits. Sure they are not important at all, but there probably won't be any earth shuttering releases over the next decade that would trigger a release. And you don't want to leave these two poor commits sitting out in the rain for so long, do you? :grinning:

**Comment by davep** [comment]
Thanks, I'll take a look. I use flyspell and have it enabled for comments and strings in code too, so goodness knows how they slipped past. Having something run in a more lint-like mode sounds like a good idea (and given my issues with writing, probably an excellent idea).

**Comment by davep** [comment]
[v2.2 tag created](https://github.com/davep/boxquote.el/releases/tag/v2.2).

**Comment by tarsius** [comment]
Thanks!

**Comment by davep** [comment]
Very much my pleasure, and thanks once again for taking the time to fix my sloppy typing. 🙂

**Pull request merged**
